export const projectsData = [
  {
    id: 1,
    name: "Lacasa Shop",
    description: "Buy all what you need online",
    date: "2023-03-18",
    demoLink: "https://lacasa-ely.netlify.app/",
  },
  {
    id: 2,
    name: "ElayyanTube",
    description: "Customize your own YouTube",
    date: "2022-10-29",
    demoLink: "https://elayyantube.netlify.app/",
  },
  {
    id: 3,
    name: "PaintToon",
    description: "Discover art and express emotions",
    date: "2024-06-10",
    demoLink: "https://mohammad-elayyan.github.io/paint_toon/",
  },
  {
    id: 4,
    name: "HealthBeat",
    description: "Discover heart parts accurately",
    date: "2024-03-21",
    demoLink: "https://mohammad-elayyan.github.io/heart-model/",
  },
  {
    id: 5,
    name: "Speak Natively",
    description: "Learn to speak like a native",
    date: "2023-09-02",
    demoLink: "https://mohammad-elayyan.github.io/words-speaking/",
  },
  {
    id: 13,
    name: "Math",
    description: "Solve and practice mathmatical problems",
    date: "2023-07-02",
    demoLink: "https://mohammad-elayyan.github.io/math/",
  },
  {
    id: 6,
    name: "Eatly",
    description: "Take care of your health",
    date: "2023-11-01",
    demoLink: "https://mohammad-elayyan.github.io/eatly/",
  },
  {
    id: 7,
    name: "Delicious",
    description: "Discover all kitchens around the world",
    date: "2022-11-05",
    demoLink: "https://mohammad-elayyan.github.io/Delicious/",
  },
  {
    id: 8,
    name: "Movies World",
    description: "Discover latest movies and series",
    date: "2023-09-17",
    demoLink: "https://mohammad-elayyan.github.io/movies-world/",
  },
  {
    id: 9,
    name: "Books",
    description: "Online Books store",
    date: "2020-10-17",
    demoLink: "https://mohammad-elayyan.github.io/Books/",
  },
  {
    id: 10,
    name: "CV",
    description: "jQuery and other libraries",
    date: "2021-02-10",
    demoLink: "https://mohammad-elayyan.github.io/Cv/",
  },
  {
    id: 11,
    name: "Blogger",
    description: "Blog interface with nice animations",
    date: "2020-11-02",
    demoLink: "https://mohammad-elayyan.github.io/Blogger/",
  },
  {
    id: 12,
    name: "Portfolio",
    description: "Nice and simple portfolio interface",
    date: "2020-01-21",
    demoLink: "https://mohammad-elayyan.github.io/Portfolio/",
  },
];

export const BtnList = [
  { label: "Home", link: "/", icon: "home", newTab: false },
  { label: "About", link: "/about", icon: "about", newTab: false },
  { label: "Projects", link: "/projects", icon: "projects", newTab: false },
  { label: "Contact", link: "/contact", icon: "contact", newTab: false },
  {
    label: "Github",
    link: "https://www.github.com/mohammad-elayyan",
    icon: "github",
    newTab: true,
  },
  {
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/mohammad-elayyan-1b8792193/",
    icon: "linkedin",
    newTab: true,
  },
  {
    label: "X",
    link: "https://x.com/mohmmadalean1/",
    icon: "twitter",
    newTab: true,
  },
  {
    label: "Resume",
    link: "/resume.pdf",
    icon: "resume",
    newTab: true,
  },
];
